#include "cms32f033x.h"
#include "define.h"

/*****************************************************************************
 ** \brief	 GPIO_ConfigRunMode
 **			 配置IO口运行模式
 ** \param [in] port : GPIO0、GPIO1 、GPIO2、GPIO3、GPIO4
 **				PinMask: GPIO_PIN_0_MSK ~ GPIO_PIN_7_MSK
 **				Mode:	 (1)GPIO_MODE_INPUT
 **						 (2)GPIO_MODE_OUTPUT
 **						 (3)GPIO_MODE_OPEN_DRAIN_WITHOUT_PULL_UP
 **						 (4)GPIO_MODE_INPUT_WITH_PULL_UP
 **						 (5)GPIO_MODE_INPUT_WITH_PULL_DOWN
 ** \return  none
 ** \note	
*****************************************************************************/


//######################### LAIYK_001 ####################################//
#if defined LAIYK_001
void GPIO_Config(void)
{	
	SYS_SET_IOCFG(IOP00CFG,SYS_IOCFG_P00_GPIO);			//电池电量ADC口	
	SYS_SET_IOCFG(IOP01CFG,SYS_IOCFG_P01_GPIO);			//外电检测

	SYS_SET_IOCFG(IOP04CFG,SYS_IOCFG_P04_GPIO);		//蜂鸣器
	SYS_SET_IOCFG(IOP05CFG,SYS_IOCFG_P05_GPIO);	//电磁阀开关
	SYS_SET_IOCFG(IOP06CFG ,SYS_IOCFG_P06_GPIO);	//真空泵开关
	SYS_SET_IOCFG(IOP07CFG ,SYS_IOCFG_P07_GPIO);
	
	SYS_SET_IOCFG(IOP10CFG,SYS_IOCFG_P10_GPIO);		
	SYS_SET_IOCFG(IOP12CFG,SYS_IOCFG_P12_GPIO);
	SYS_SET_IOCFG(IOP13CFG,SYS_IOCFG_P13_GPIO);
	SYS_SET_IOCFG(IOP14CFG,SYS_IOCFG_P14_GPIO);
	SYS_SET_IOCFG(IOP15CFG,SYS_IOCFG_P15_GPIO);			//电池指示灯
	
	SYS_SET_IOCFG(IOP21CFG,SYS_IOCFG_P21_GPIO);			//电机到位检测
	SYS_SET_IOCFG(IOP22CFG,SYS_IOCFG_P22_GPIO);
	SYS_SET_IOCFG(IOP23CFG,SYS_IOCFG_P23_GPIO);
	SYS_SET_IOCFG(IOP24CFG,SYS_IOCFG_P24_GPIO);			//气压检测
	SYS_SET_IOCFG(IOP25CFG,SYS_IOCFG_P25_GPIO);
	SYS_SET_IOCFG(IOP26CFG,SYS_IOCFG_P26_GPIO);
	
	SYS_SET_IOCFG(IOP30CFG,SYS_IOCFG_P30_GPIO);//气泵指示灯
	SYS_SET_IOCFG(IOP31CFG,SYS_IOCFG_P31_GPIO);//堵粮指示灯
	SYS_SET_IOCFG(IOP32CFG,SYS_IOCFG_P32_GPIO);//余粮指示灯
	
	SYS_SET_IOCFG(IOP34CFG,SYS_IOCFG_P34_GPIO);//喂食检测灯
	SYS_SET_IOCFG(IOP35CFG,SYS_IOCFG_P35_GPIO);//余粮检测灯

	SYS_SET_IOCFG(IOP36CFG,SYS_IOCFG_P36_GPIO);

	SYS_SET_IOCFG(IOP40CFG,SYS_IOCFG_P40_GPIO);
	SYS_SET_IOCFG(IOP43CFG,SYS_IOCFG_P43_GPIO);	//配网指示灯
	SYS_SET_IOCFG(IOP44CFG,SYS_IOCFG_P44_GPIO);//卡粮指示灯	


	GPIO_CONFIG_IO_MODE(GPIO0,GPIO_PIN_0,GPIO_MODE_INPUT_WITH_PULL_UP);
	GPIO_CONFIG_IO_MODE(GPIO0,GPIO_PIN_1,GPIO_MODE_INPUT_WITH_PULL_UP);
	
	GPIO_CONFIG_IO_MODE(GPIO0,GPIO_PIN_4,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO0,GPIO_PIN_5,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO0,GPIO_PIN_6,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO0,GPIO_PIN_7,GPIO_MODE_OUTPUT);
	
	GPIO_CONFIG_IO_MODE(GPIO1,GPIO_PIN_0,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO1,GPIO_PIN_2,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO1,GPIO_PIN_3,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO1,GPIO_PIN_4,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO1,GPIO_PIN_5,GPIO_MODE_OUTPUT);

	GPIO_CONFIG_IO_MODE(GPIO2,GPIO_PIN_1,GPIO_MODE_INPUT_WITH_PULL_UP);
	GPIO_CONFIG_IO_MODE(GPIO2,GPIO_PIN_2,GPIO_MODE_INPUT_WITH_PULL_UP);
	GPIO_CONFIG_IO_MODE(GPIO2,GPIO_PIN_3,GPIO_MODE_INPUT_WITH_PULL_UP);
	GPIO_CONFIG_IO_MODE(GPIO2,GPIO_PIN_4,GPIO_MODE_INPUT_WITH_PULL_UP);
	
	GPIO_CONFIG_IO_MODE(GPIO2,GPIO_PIN_5,GPIO_MODE_INPUT_WITH_PULL_UP);
	GPIO_CONFIG_IO_MODE(GPIO2,GPIO_PIN_6,GPIO_MODE_INPUT_WITH_PULL_UP);
	
	GPIO_CONFIG_IO_MODE(GPIO3,GPIO_PIN_0,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO3,GPIO_PIN_1,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO3,GPIO_PIN_2,GPIO_MODE_OUTPUT);
	
	GPIO_CONFIG_IO_MODE(GPIO3,GPIO_PIN_4,GPIO_MODE_INPUT_WITH_PULL_UP);
	GPIO_CONFIG_IO_MODE(GPIO3,GPIO_PIN_5,GPIO_MODE_INPUT_WITH_PULL_UP);
	
	GPIO_CONFIG_IO_MODE(GPIO3,GPIO_PIN_6,GPIO_MODE_OUTPUT);

	GPIO_CONFIG_IO_MODE(GPIO4,GPIO_PIN_0,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO4,GPIO_PIN_3,GPIO_MODE_OUTPUT);
	GPIO_CONFIG_IO_MODE(GPIO4,GPIO_PIN_4,GPIO_MODE_OUTPUT);	
	
	/*
	(2)设置中断为下降沿中断模式
	*/	
//	GPIO_EnableInt(GPIO2,GPIO_PIN_5_MSK,GPIO_INT_EDGE_FALLING);
	GPIO_EnableInt(GPIO2,GPIO_PIN_6_MSK,GPIO_INT_EDGE_FALLING);
	/*
	(3)设置 IO口输入滤波		
	*/		
//	GPIO_EnableFilter(GPIO2,GPIO_PIN_5_MSK,GPIO_FILCLK_DIV_10);
	GPIO_EnableFilter(GPIO2,GPIO_PIN_6_MSK,GPIO_FILCLK_DIV_10);
	/*
	(4)设置GPIO中断
	*/
//	GPIO_ClearIntFlag(GPIO2,GPIO_PIN_5);	/*清除中断标志位*/
	GPIO_ClearIntFlag(GPIO2,GPIO_PIN_6);	/*清除中断标志位*/
	NVIC_EnableIRQ(GPIO2_IRQn);				/*开启GPIO中断*/
	/*
	(5)设置GPIO中断优先级
	*/	
	NVIC_SetPriority(GPIO2_IRQn,3);			/* 0~3, 0最高, 3最低*/
	
	
	
	WIFI_PWR			= 1;			//wifi电源控制
	BUZZER_EN			= 0;			//蜂鸣器控制脚
	SWITCH_DRIVER		= 0;			//电磁阀开关
	MOTOR_DRIVER		= 0;			//真空泵开关
	IR_LED_CTRL			= 1;			//红外对管检测（所有对管）

	MOTOR_FEED_G		= 0;			//喂食电机正转
	MOTOR_FEED_B		= 0;			//喂食电机反转
	MOTOR_DOOR_G		= 0;			//门仓电机正转
	MOTOR_DOOR_B		= 0;			//门仓电机反转

	LED_DRIVER			= LED_ON;			//氛围灯
	BAT_LED				= LED_OFF;			//外电指示灯
	LINK_LED			= LED_OFF;			//网络指示灯
	PUMP_LED			= LED_OFF;			//气泵工作指示灯
	FEED_LED			= LED_OFF;			//卡粮指示灯
	MOTOR_LED			= LED_OFF;			//堵粮指示灯
	FOOD_LED			= LED_OFF;			//余粮指示灯

	MOTOR_DET			= 1;			//喂食到位
	FEED_DET			= 1;			//堵粮对管到位
	FOOD_DET			= 1;			//余粮对管到位
	DOOR_DET_P			= 1;			//门仓到位P
	DOOR_DET_N			= 1;			//门仓到位N
	AIR_DET				= 1;			//气泵到位

	FEED_KEY			= 1;			//喂食按键
	RESET_KEY			= 1;			//复位按键
}
#endif
//######################### V86 ####################################//




